### ISSUE TITLE
No header coloring until you edit the MD file

### ISSUE THREAD

**Issue by Yzrsah** [satokaz/vscode-markdown-header-coloring#11]
On VSCode Insiders 1.32:

Markdown header coloring is not enabled until after you edit the markdown.

**Comment by satokaz** [comment]
@Yzrsah 

Is it colored when you switch files or tabs?

**Comment by satokaz** [comment]
@Yzrsah 

Can you install the following version and check it?

[vscode-markdown-header-coloring-0.1.2.vsix.zip](https://github.com/satokaz/vscode-markdown-header-coloring/files/2867429/vscode-markdown-header-coloring-0.1.2.vsix.zip)

**Comment by Yzrsah** [comment]
With the last update to Insiders it has started working again.

I will keep you updated and close issue soon
