### ISSUE TITLE
Lately the decorators have been moving

### ISSUE THREAD

**Issue by altimmons** [satokaz/vscode-markdown-header-coloring#22]
The decorator seems to be migrating away from where its supposed to be.  I have seen this on at least 2 separate machines.  These two machines have different though similar configuration.  I cannot tell what is causing it.  Even with all extensions disabled by a few, it seems to occur.  I highlighted where I expected the header to occur, and where it is occuring should be obvious.  This happens very early in the file and in most (all?) md files.

Any ideas?

![MarkdownHeader](https://user-images.githubusercontent.com/15314341/57723541-73923880-764e-11e9-9047-a0d40c66f404.png)

In a few weeks I am going to start working on a markdown package of my own.  I want to take my favorite ideas and put them together,  I've not done js or node before, so I wouldn't bother getting that excited.  But I've been collecting the ideas that I like.

**Comment by altimmons** [comment]
Ok- I;ve watched it for a while.  They "tick" down each time the formatter is engaged.
![image](https://user-images.githubusercontent.com/15314341/57723950-6164ca00-764f-11e9-9a46-6d44bd36dbd9.png)

Watch as I bold this word:
  
![image](https://user-images.githubusercontent.com/15314341/57723998-77728a80-764f-11e9-8ba2-01e90f316926.png)
This is a bit better watch as I type a sentence.

![VSCode Issue](https://user-images.githubusercontent.com/15314341/57724720-1946a700-7651-11e9-8ab8-304555757bc9.gif)

**Comment by satokaz** [comment]
Thank you for the report.

I'm interested in how that md file is processed.
Can you give me a sample md file?

**Comment by satokaz** [comment]
@altimmons 

> I'm interested in how that md file is processed.
> Can you give me a sample md file?

Or can you confirm it with attached 0.1.7?

[vscode-markdown-header-coloring-0.1.7.vsix.zip](https://github.com/satokaz/vscode-markdown-header-coloring/files/3181988/vscode-markdown-header-coloring-0.1.7.vsix.zip)

**Comment by satokaz** [comment]
@altimmons 

I think the same problem as # 23.
I published 0.1.7 to the marketplace.
