### ISSUE TITLE
lastest vscode version is not work this extension. 

### ISSUE THREAD

**Issue by kksworks** [satokaz/vscode-markdown-header-coloring#23]
thanks for your extension.

vscode lastest version is not working.

![img_1086](https://user-images.githubusercontent.com/8262405/58016713-5ae7be00-7b39-11e9-8cc0-6dfd32812851.png)

highlight is something wrong display line.
![img_1087](https://user-images.githubusercontent.com/8262405/58016699-4e636580-7b39-11e9-9f06-d66eb3a3bf78.png)

**Comment by satokaz** [comment]
@kksworks 

Is the markdown contents of the paste image all displayed?
Do ``` or  --- appear before or after?

Paste the screenshot in my environment
<img width="681" alt="image" src="https://user-images.githubusercontent.com/13635244/58077437-7d381500-7be7-11e9-976a-6c3f5180429a.png">

**Comment by satokaz** [comment]
@kksworks 

Please tell me one more thing, 
Windows environment?

**Comment by satokaz** [comment]
@kksworks 

Sorry, it was Windows.
I did not consider handling of line breaks due to platform differences.

0.1.7 has been published to the marketplace.

**Comment by kksworks** [comment]
Wow!! new version works great!!

Thank you very much.

Your extension make me happy. ^^

![img_1100](https://user-images.githubusercontent.com/8262405/58137026-6c30e780-7c6b-11e9-8a91-c56e38c1fd12.png)
