### ISSUE TITLE
Commented Front matter entries should be ignored

### ISSUE THREAD

**Issue by iaeiou** [satokaz/vscode-markdown-header-coloring#30]
Hi there,

this extension works great, thanks!

A minor issue occurs when commenting out a variable in the front matter. For example:

```
---
title: "Roadmap"
date: 2021-12-22T00:00:03+00:00
# weight: 1
---

## This is the first title
```

The line containing `weight` is detected as a Heading and styling is applied.

I'm using Vscodium 1.63.2, and here are my settings:

```
          "markdown-header-coloring.userDefinedHeaderColor": {
            "enabled": true,
            "Header_1": {
              "color": "#da2c60",
              "textDecoration": "font-weight: 600; font-size: 2.4em;background:none;"
            },
            "Header_2": {
              "color": "#da2c60",
              "textDecoration": "font-weight: 600; font-size: 2.4em;background:none;"
            },
            "Header_3": {
              "color": "#da2c60CC",
              "textDecoration": "font-weight: 600; font-size: 1.8em;background:none;"
            },
            "Header_4": {
              "color": "#7e1937",
              "textDecoration": "font-weight: 600; font-size: 1.4em;background:none;"
            },
          },
```

Thanks!

**Comment by satokaz** [comment]
@iaeiou 
Thank you for your suggestion.

I applied a quick change.
Can you confirm that it is working as expected?

[vscode-markdown-header-coloring-0.1.9.vsix.zip](https://github.com/satokaz/vscode-markdown-header-coloring/files/7949141/vscode-markdown-header-coloring-0.1.9.vsix.zip)


![image](https://user-images.githubusercontent.com/13635244/151329170-7694f25a-adb3-4ef3-9666-43b84351e640.png)

**Comment by iaeiou** [comment]
Your fix works!
That was fast, I'm impressed, that's much appreciated.
Thank you!

**Comment by satokaz** [comment]
@iaeiou 

Thank you for checking.
Please wait until it is published on the marketplace.

**Comment by iaeiou** [comment]
Alright, I'll let you close this issue when it's the right time for you. Thanks again!

**Comment by satokaz** [comment]
@iaeiou 

Published to marketplace.
